import React from 'react';

const Categories = () => {
  return (
    <aside>
    
      <ul>
        <li><a href="https://www.google.com/search?q=kurtha+images&rlz=1C1UEAD_enIN1084IN1084&oq=kurtha+images&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIJCAEQABgKGIAEMgkIAhAAGAoYgAQyCQgDEAAYChiABDIJCAQQABgKGIAEMgkIBRAAGAoYgAQyCQgGEAAYChiABDIJCAcQABgKGIAEMgkICBAAGAoYgAQyDAgJEAAYChgPGBYYHtIBCTYyMDFqMGoxNagCCLACAQ&sourceid=chrome&ie=UTF-8">Category 1</a></li>
        <li><a href="https://www.google.com/search?q=toys+images&sca_esv=76a168b65a348735&sca_upv=1&rlz=1C1UEAD_enIN1084IN1084&sxsrf=ACQVn0_xW9koIUq7Kw7G7uM0sLaMPkjx_w%3A1714486479176&ei=z_wwZrWgCtWQ4-EP8OqC-Ak&ved=0ahUKEwj1w8Dsj-qFAxVVyDgGHXC1AJ8Q4dUDCBA&uact=5&oq=toys+images&gs_lp=Egxnd3Mtd2l6LXNlcnAiC3RveXMgaW1hZ2VzMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABEi8IlDFDFjoIHABeAGQAQCYAcwBoAHzDaoBBjAuMTAuMbgBA8gBAPgBAZgCDKACtA6oAhLCAgcQIxgnGOoCwgIUEAAYgAQY4wQYtAIY6QQY6gLYAQHCAgQQIxgnwgIKECMYgAQYJxiKBcICERAAGIAEGJECGLEDGIMBGIoFwgILEAAYgAQYsQMYgwHCAhEQLhiABBixAxjRAxiDARjHAcICCxAuGIAEGLEDGIMBwgILEAAYgAQYkQIYigXCAhAQLhiABBjRAxhDGMcBGIoFwgIKEAAYgAQYQxiKBcICEBAAGIAEGLEDGIMBGIoFGArCAg4QABiABBixAxiDARiKBcICDRAAGIAEGLEDGEMYigXCAg4QLhiABBixAxjRAxjHAcICCxAAGIAEGJIDGIoFwgIIEAAYgAQYyQPCAggQABiABBixA8ICCxAAGIAEGLEDGIoFwgIUEAAYgAQYkQIYsQMYgwEYyQMYigXCAgoQABiABBgUGIcCmAMUugYGCAEQARgBkgcGMS4xMC4xoAe1RQ&sclient=gws-wiz-serp">Category 2</a></li>
        <li><a href="https://www.google.com/search?q=accessories+images&sca_esv=76a168b65a348735&sca_upv=1&rlz=1C1UEAD_enIN1084IN1084&sxsrf=ACQVn0-M2DFZV3bN7stk5aQ-Uj5Vd2mhtQ%3A1714486510083&ei=7vwwZujVBMGT4-EP2Y6v0Ag&oq=acce&gs_lp=Egxnd3Mtd2l6LXNlcnAiBGFjY2UqAggAMgoQIxiABBgnGIoFMgsQABiABBiRAhiKBTINEAAYgAQYsQMYQxiKBTIREC4YgAQYsQMY0QMYgwEYxwEyChAAGIAEGEMYigUyCBAAGIAEGLEDMgsQABiABBixAxiDATILEAAYgAQYsQMYgwEyCBAAGIAEGLEDMggQABiABBixA0icI1CNDVj2EXABeAGQAQCYAcgBoAHiBaoBBTAuMy4xuAEByAEA-AEBmAIFoAKQBqgCFMICBxAjGCcY6gLCAhMQABiABBhDGLQCGIoFGOoC2AEBwgIEECMYJ8ICFhAuGIAEGLEDGNEDGEMYgwEYxwEYigXCAgoQLhiABBhDGIoFwgIOEC4YgAQYsQMYgwEYigXCAgUQABiABMICFBAuGIAEGLEDGNEDGIMBGMcBGMkDwgIOEAAYgAQYsQMYgwEYigXCAgsQABiABBiSAxiKBZgDEboGBggBEAEYAZIHBTEuMS4zoAfGLQ&sclient=gws-wiz-serp">Category 3</a></li>
        {/* Add more categories as needed */}
      </ul>
    </aside>
  );
};

export default Categories;
